name: Setup Project
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run setup script
        run: bash setup.sh
      - name: Commit files
        run: |
          git config --global user.email "beeprorussia@gmail.com"
          git config --global user.name "Viktoriya"
          git add -A
          git commit -m "Create all project files" || echo "Nothing to commit"
          git push
